{
  "input": {
    "input_file_name": "/Users/nicolasbize/alice/fresh-analysis/Analysis_Data/LHC22q/mass_lhc22q_pass3_Chi2Cuts.root",
    "input_name": "hMassChi2is0to34",
    "pdf_dictionary": {
      "pdf": ["CB2", "CB2", "VWG", "SUM"],
      "pdfName": ["Jpsi", "Psi2s", "Bkg", "SUM"],
      "pdfColor": [861, 417, 1],
      "pdfNameForLegend": ["J/#psi", "Psi2s","Background", "Fit"],
      "pdfStyle": [1, 1, 2],
      "parFix": [
        [False, False, True, True, True, True],
        [False, False, True, True, True, True],
        [False, False, False],
        [False, False, False]
      ],
      "parVal": [
        [3.097, 0.72e-01, 0.78, 3.6, 1.25, 1.8],
        [3.68, 1.5e-01, 1.089, 3.393, 2.097, 8.694],
        [1, 1, 1],
        [100, 100, 1000]
      ],
      "parLimMin": [
        [2.9, 5.0e-02, 0.0889, 1.3929, 1., 1.5.],
        [3.2, 7.0e-02, 1.0889, 3.3929, 2.096, 8.693],
        [-10, 0, -100],
        [0, 0, 0]
      ],
      "parLimMax": [
        [3.2, 1.5e-01, 1.0891, 3.3931, 1.5., 1.8.],
        [3.9, 1.9e-01, 1.0891, 3.3931, 2.098, 8.695],
        [10, 100, 100],
        [5000, 1000, 80000]
      ],
      "parName": [
        ["mean_Jpsi", "width_Jpsi", "a_Jpsi", "b_Jpsi", "c_Jpsi", "d_Jpsi"],
        ["sum::mean_Psi2s(mean_Jpsi,0.584)", "prod::width_Psi2s(width_Jpsi,1.05)", "a_Psi2s", "b_Psi2s", "c_Psi2s", "d_Psi2s"],
        ["aa", "bb", "cc"],
        ["sig_Jpsi", "sig_Psi2s", "bkg"]
      ],
      "fitRangeMin": [2],
      "fitRangeMax": [5],
      "fitMethod": "likelyhood",
      "doResidualPlot": true,
      "doPullPlot": true, 
      "doCorrMatPlot": true,
      "doAlicePlot": true,
      "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
      "parNameForAlicePlot": ["m_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}"],
      "text": [
        [0.20, 0.87, "LHC22q, apass3, pp #sqrt{#it{s}} = 13.6 TeV"], 
        [0.20, 0.80, "2.5 < #it{y} < 3.6, J/#psi #rightarrow #mu^{+}#mu^{-}"],
        [0.20, 0.73, "MFT+MCH+MID"],
        [0.20, 0.66, "#chi^{2}_{MCH-MFT} < 34"]
      ]
    }
  },
  "output": {
    
    
    "output_file_name": "output/22q/"
  }
}
