{
  "input": {
    "input_file_name": "/Users/nicolasbize/alice/fresh-analysis/Analysis_Data/LHC22o/pass3/mass_lhc22o_apass3_Chi2Cuts_corr.root",
    "input_name": "hMassChi2is0to45",
    "pdf_dictionary": {
      "pdf": ["CB2", "VWG", "SUM"],
      "pdfName": ["Jpsi", "Bkg", "SUM"],
      "pdfColor": [861, 1],
      "pdfNameForLegend": ["J/#psi","Background", "Fit"],
      "pdfStyle": [1, 2],
      "parFix": [
        [False, False, False, False, False, False],
        [False, False, False],
        [False, False, False]
      ],
      "parVal": [
        [3.096, 1.2e-01, 1.089, 3.393, 2.097, 8.694],
        [1, 1, 1],
        [100, 1000]
      ],
      "parLimMin": [
        [2.9, 7.0e-02, 1.0889, 3.3929, 2.096, 8.693],
        [-10, 0, -100],
        [0, 0]
      ],
      "parLimMax": [
        [3.5, 2.3e-01, 1.0891, 3.3931, 2.098, 8.695],
        [10, 100, 100],
        [100000, 500000]
      ],
      "parName": [
        ["mean_Jpsi", "width_Jpsi", "a_Jpsi", "b_Jpsi", "c_Jpsi", "d_Jpsi"],
        ["aa", "bb", "cc"],
        ["sig_Jpsi", "bkg"]
      ],
      "fitRangeMin": [2],
      "fitRangeMax": [5],
      "fitMethod": "likelyhood",
      "doResidualPlot": true,
      "doPullPlot": true, 
      "doCorrMatPlot": true,
      "doAlicePlot": true,
      "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
      "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}"],
      "text": [
        [0.20, 0.87, "LHC22o, apass3, pp #sqrt{#it{s}} = 13.6 TeV"], 
        [0.20, 0.80, "2.5 < #it{y} < 3.6, J/#psi #rightarrow #mu^{+}#mu^{-}"],
        [0.20, 0.73, "MFT+MCH+MID"],
        [0.20, 0.66, "#chi^{2}_{MCH-MFT} < 45"]
      ]
    }
  },
  "output": {
    
    
    "output_file_name": "output/pass3/"
  }
}
