{
    "input": {
      "input_file_name": "/Users/nicolasbize/alice/fresh-analysis/Analysis_Data/psi2sToJpsi/LHC22o_medium_apass4/differentialintegrated.root",
      "input_name": [
        "mass_integrated"
      ],
      "pdf_dictionary": {
        "pdf": ["CB2", "VWG", "SUM"],
        "pdfName": ["Jpsi", "Bkg", "SUM"],
        "pdfColor": [861, 1],
        "pdfNameForLegend": ["J/#psi","Background", "Fit"],
        "pdfStyle": [1, 2],
        "parVal": [
          [3.096, 0.8e-01, 1.089, 3.393, 2.097, 8.694],
          [1, 1, 1],
          [10000, 1000000]
        ],
        "parLimMin": [
          [2.9, 7.0e-02, 0, 0, 0, 0],
          [-10, 0, -100],
          [100, 1000]
        ],
        "parLimMax": [
          [3.5 1.9e-01, 5, 5, 5, 15],
          [10, 100, 100],
          [500000, 5000000]
        ],
        "parName": [
          ["mean_Jpsi", "width_Jpsi", "a_Jpsi", "b_Jpsi", "c_Jpsi", "d_Jpsi"],
          ["aa", "bb", "cc"],
          ["sig_Jpsi", "bkg"]
        ],
        "fitRangeMin": [2,2.1],
        "fitRangeMax": [5, 4.9],
        "fitMethod": "likelyhood",
        "doResidualPlot": true,
        "doPullPlot": true, 
        "doCorrMatPlot": true,
        "doAlicePlot": true,
        "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
        "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}"],
        "text": [
          [0.20, 0.87, "LHC22o CB2+VWG, #sqrt{#it{s}} = 13.6 TeV"], 
          [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
        ]
      },
      "analysis_dictionary": {
        "parName": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
        "input_name_pt": [
        ],
        "ptMin": [0., 1., 2., 3., 5., 7., 10.],
        "ptMax": [1., 2., 3., 5., 7., 10., 20],
        "input_name_y": [
        ],
        "yMin": [2.50, 2.75, 3.00, 3.25, 3.50, 3.75],
        "yMax": [2.75, 3.00, 3.25, 3.50, 3.75, 4.00],
      }
    },
    "output": {
      "output_file_name": "output/analysis/LHC22o_medium_apass4_tails_extraction/"
    }
  }