{
  "input": {
    "input_file_name": "/Users/nicolasbize/alice/fresh-analysis/Analysis_Data/psi2sToJpsi/LHC22o_medium_apass4/differential_pT.root",
    "input_name": ["pt_0_1","pt_1_2","pt_2_3","pt_3_4","pt_4_5","pt_5_7","pt_7_10","pt_10_20"],
    "pdf_dictionary": {
      "pdf": ["NA60", "NA60", "Pol4Exp", "SUM"],
      "pdfName": ["Jpsi", "Psi2s", "Bkg", "SUM"],
      "pdfColor": [861, 417, 1],
      "pdfNameForLegend": ["J/#psi", "Background", "Fit"],
      "pdfStyle": [1, 1, 2],
      "parVal": [
        [3.096, 1.2e-01,  -1.0000e+00, 1.7325e-01, 1.0000e+00, 6.0226e-06, 2.1614e+00, 6.1800e-02, 1.3388e+00,  7.0872e-03],
        [3.68, 1.5e-01,  -1.0000e+00, 1.7325e-01, 1.0000e+00, 6.0226e-06, 2.1614e+00, 6.1800e-02, 1.3388e+00,  7.0872e-03],
        [1, 1, 1, 1, 1, 2],
        [1000, 100, 100000]
      ],
      "parLimMin": [
        [2.9, 7.0e-02,  -1.0000e+00, 1.7325e-01, 1.0000e+00, 6.0226e-06, 2.1614e+00, 6.1800e-02, 1.3388e+00,  7.0872e-03],
        [3.68, 7.0e-02,   -1.0000e+00, 1.7325e-01, 1.0000e+00, 6.0226e-06, 2.1614e+00, 6.1800e-02, 1.3388e+00,  7.0872e-03],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0]
      ],
      "parLimMax": [
        [3.5, 1.9e-01,   -1.0000e+00, 1.7325e-01, 1.0000e+00, 6.0226e-06, 2.1614e+00, 6.1800e-02, 1.3388e+00,  7.0872e-03],
        [3.68, 1.9e-01,   -1.0000e+00, 1.7325e-01, 1.0000e+00, 6.0226e-06, 2.1614e+00, 6.1800e-02, 1.3388e+00,  7.0872e-03],
        [100, 100, 100, 100, 100, 100],
        [50000, 5000, 500000]
      ],
      "parName": [
        ["mean_Jpsi", "width_Jpsi", "alphaL_Jpsi", "p1L_Jpsi", "p2L_Jpsi", "p3L_Jpsi", "alphaR_Jpsi", "p1R_Jpsi", "p2R_Jpsi", "p3R_Jpsi"],
        ["mean_Psi2s", "width_Psi2s", "alphaL_Psi2s", "p1L_Psi2s", "p2L_Psi2s", "p3L_Psi2s", "alphaR_Psi2s", "p1R_Psi2s", "p2R_Psi2s", "p3R_Psi2s"],
        ["aa", "bb", "cc","dd", "ee", "ff"],
        ["sig_Jpsi", "sig_Psi2s", "bkg"]
      ],
      "fitRangeMin": [2,2.2, 2.4],
      "fitRangeMax": [5,4.8, 4.6],
      "fitMethod": "likelyhood",
      "doResidualPlot": true,
      "doPullPlot": true, 
      "doCorrMatPlot": true,
      "doAlicePlot": true,
      "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
      "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}"],
      "text": [
        [0.20, 0.87, "LHC22o NA60+Pol4Exp, #sqrt{#it{s}} = 13.6 TeV"], 
        [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
      ]
    },
    "analysis_dictionary": {
        "parName": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi", "sig_Psi2s"],
        "input_name_pt": [
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_0_1.root",
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_1_2.root",
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_2_3.root", 
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_3_4.root", 
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_4_5.root", 
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_5_7.root", 
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_7_10.root", 
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/pt_10_20.root", 
        ],
        "ptMin": [0., 1., 2., 3., 4.,5.,7.,10.],
        "ptMax": [1., 2., 3., 4., 5.,7.,10.,20.],
        # "input_name_y": [
        # ],
        # "yMin": [2.50],
        # "yMax": [2.75],
      }
  },
  "output": {
    
    "output_file_name": "output/analysis/LHC22o_medium_apass4_data_run3_tails/"
  }
}