{
    "input": {
      "input_file_name": "/Users/lucamicheletti/cernbox/JPSI/Run3/2022/apass4/LHC22o_medium/AnalysisResultsHistograms.root",
      "input_name": [
        "hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_0_1",
        #"hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_1_2",
        #"hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_2_3",
        #"hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_3_4",
        #"hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_4_5"
      ],
      "pdf_dictionary": {
        "pdf": ["CB2", "CB2", "Pol4Exp", "SUM"],
        "pdfName": ["Jpsi", "Psi2s", "Bkg", "SUM"],
        "pdfColor": [861, 417, 1],
        "pdfNameForLegend": ["J/#psi", "#psi(2S)","Background", "Fit"],
        "pdfStyle": [1, 1, 2],
        "parVal": [
          [3.096, 0.8e-01, 1.089, 3.393, 2.097, 8.694],
          [3.68, 0.8e-01, 1.089, 3.393, 2.097, 8.694],
          [1, 1, 1, 1, 1, 2],
          [10000, 10, 10000]
        ],
        "parLimMin": [
          [2.9, 7.0e-02, 1.089, 3.393, 2.097, 8.694],
          [3.2, 7.0e-02, 1.089, 3.393, 2.097, 8.694],
          [0, 0, 0, 0, 0, 0],
          [0, 0, 0]
        ],
        "parLimMax": [
          [3.5, 1.5e-01, 1.089, 3.393, 2.097, 8.694],
          [3.9, 1.5e-01, 1.089, 3.393, 2.097, 8.694],
          [10, 10, 10, 10, 10, 10],
          [50000, 5000, 5000000]
        ],
        "parName": [
          ["mean_Jpsi", "width_Jpsi", "a_Jpsi", "b_Jpsi", "c_Jpsi", "d_Jpsi"],
          ["sum::mean_Psi2s(mean_Jpsi,0.584)", "prod::width_Psi2s(width_Jpsi,1.05)", "a_Psi2s", "b_Psi2s", "c_Psi2s", "d_Psi2s"],
          ["aa", "bb", "cc","dd", "ee", "ff"],
          ["sig_Jpsi", "sig_Psi2s", "bkg"]
        ],
        #"fitRangeMin": [2, 2.2, 2.4],
        #"fitRangeMax": [5, 4.8, 4.6],
        "fitRangeMin": [2],
        "fitRangeMax": [5],
        "fitMethod": "likelyhood",
        "doResidualPlot": true,
        "doPullPlot": true, 
        "doCorrMatPlot": true,
        "doAlicePlot": true,
        "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi", "sig_Psi2s"],
        "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}", "#it{N}_{#psi(2S)}"],
        "text": [
          [0.20, 0.87, "LHC22o CB2+Pol4Exp, #sqrt{#it{s}} = 13.6 TeV"], 
          [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
        ]
      },
      "analysis_dictionary": {
        "parName": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi", "sig_Psi2s"],
        "input_name_pt": [
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_0_1__2_5.root",
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_1_2__2_5.root",
        ],
        "ptMin": [0., 1., 2., 3., 4.],
        "ptMax": [1., 2., 3., 4., 5.],
        "input_name_y": [
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_2.50_2.75__2_5.root",
        ],
        "yMin": [2.50],
        "yMax": [2.75],
      }
    },
    "output": {
      "output_file_name": "output/analysis/LHC22o_medium_apass4_data_run2_tails/"
    }
  }