{
    "input": {
      "input_file_name": "/Users/lucamicheletti/cernbox/JPSI/Run3/2022/apass4/LHC22o_medium/AnalysisResultsHistograms.root",
      "input_name": [
        "hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_2.50_2.75",
        "hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_2.75_3.00",
        "hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_3.00_3.25",
        "hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_3.25_3.50",
        "hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_3.50_3.75",
        "hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_3.75_4.00",
      ],
      "pdf_dictionary": {
        "pdf": ["CB2", "CB2", "VWG", "SUM"],
        "pdfName": ["Jpsi", "Psi2s", "Bkg", "SUM"],
        "pdfColor": [861, 417, 1],
        "pdfNameForLegend": ["J/#psi", "#psi(2S)","Background", "Fit"],
        "pdfStyle": [1, 1, 2],
        "parVal": [
          [3.096, 0.8e-01, 1.1407, 4.6530, 2.2905, 5.3774e-01],
          [3.68, 0.8e-01, 1.1407, 4.6530, 2.2905, 5.3774e-01],
          [1, 1, 1],
          [100, 1, 100000]
        ],
        "parLimMin": [
          [2.9, 7.0e-02, 1.1407, 4.6530, 2.2905, 5.3774e-01],
          [3.2, 7.0e-02, 1.1407, 4.6530, 2.2905, 5.3774e-01],
          [-10, 0, -100],
          [10, 0, 1000]
        ],
        "parLimMax": [
          [3.5, 1.9e-01, 1.1407, 4.6530, 2.2905, 5.3774e-01],
          [3.9, 1.9e-01, 1.1407, 4.6530, 2.2905, 5.3774e-01],
          [10, 100, 100],
          [50000, 500, 5000000]
        ],
        "parName": [
          ["mean_Jpsi", "width_Jpsi", "a_Jpsi", "b_Jpsi", "c_Jpsi", "d_Jpsi"],
          ["sum::mean_Psi2s(mean_Jpsi,0.584)", "prod::width_Psi2s(width_Jpsi,1.05)", "a_Psi2s", "b_Psi2s", "c_Psi2s", "d_Psi2s"],
          ["aa", "bb", "cc"],
          ["sig_Jpsi", "sig_Psi2s", "bkg"]
        ],
        #"fitRangeMin": [2, 2.2, 2.4],
        #"fitRangeMax": [5, 4.8, 4.6],
        "fitRangeMin": [2],
        "fitRangeMax": [5],
        "fitMethod": "likelyhood",
        "doResidualPlot": true,
        "doPullPlot": true, 
        "doCorrMatPlot": true,
        "doAlicePlot": true,
        "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi", "sig_Psi2s"],
        "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}", "#it{N}_{#psi(2S)}"],
        "text": [
          [0.20, 0.87, "LHC22o CB2+VWG, #sqrt{#it{s}} = 13.6 TeV"], 
          [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
        ]
      },
      "analysis_dictionary": {
        "parName": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi", "sig_Psi2s"],
        "input_name_pt": [
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_0_1__2_5.root",
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/hist_mass_pt_all_histo_PairsMuonSEPM_matchedMchMid_pt_1_2__2_5.root",
        ],
        "ptMin": [0., 1., 2., 3., 4., 5., 7., 10.],
        "ptMax": [1., 2., 3., 4., 5., 7., 10., 20.],
        "input_name_y": [
        "output/analysis/LHC22o_medium_apass4_data_run3_tails/hist_mass_y_all_histo_PairsMuonSEPM_matchedMchMid_y_2.50_2.75__2_5.root",
        ],
        "yMin": [2.50, 2.75, 3.00, 3.25, 3.50, 3.75],
        "yMax": [2.75, 3.00, 3.25, 3.50, 3.75, 4.00],
      }
    },
    "output": {
      "output_file_name": "output/analysis/LHC22o_medium_apass4_data_run3_tails/nicolas_results"
    }
  }