{
  "input": {
    "input_file_name": "/Users/nicolasbize/alice/fresh-analysis/Analysis_Data/psi2sToJpsi/LHC21i3d2/MC_signal.root",
    "input_name": [
      "data_mass_smeared"
      ],
    "pdf_dictionary": {
      "pdf": ["NA60", "SUM"],
      "pdfName": ["Jpsi", "SUM"],
      "pdfColor": [861, 1],
      "pdfNameForLegend": ["J/#psi", "Fit"],
      "pdfStyle": [1, 2],
      "parVal": [
        [3.097, 1.2e-01,  -0.83, 0.01, 0.44, 0.223, 2., 0.184, 1.295,  0.065],
        #[3.097, 1.2e-01,  -8.4264e-01, 1.5681e-01, 8.4235e-01, 2.5171e-03, 2.0054e+00, 3.4342e-02, 1.2939e+00,  7.5424e-03],
        #[3.097, 1.2e-01,  -8.2499e-01, 1.5782e-01, 1.0542e+00, 1.0037e-02, 1.9942e+00, 2.6443e-02, 5.2821e-01, 6.6852e-02],
        [1.e+6]
      ],
      "parLimMin": [
        [2.8, 7.0e-02,  0., 0., 0., 0., 0., 0., 0.,  0.],
        [0]
      ],
      "parLimMax": [
        [3.2, 1.9e-01,    5., 2., 3., 2., 15., 3., 3., 2.],
        [2.e+6]
      ],
      "parName": [
        ["mean_Jpsi", "width_Jpsi", "alphaL_Jpsi", "p1L_Jpsi", "p2L_Jpsi", "p3L_Jpsi", "alphaR_Jpsi", "p1R_Jpsi", "p2R_Jpsi", "p3R_Jpsi"],
        ["sig_Jpsi"]
      ],
      "fitRangeMin": [2],
      "fitRangeMax": [5],
      "fitMethod": "likelyhood",
      "doResidualPlot": true,
      "doPullPlot": true, 
      "doCorrMatPlot": true,
      "doAlicePlot": true,
      "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
      "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}"],
      "text": [
        [0.20, 0.87, "LHC22o NA60, #sqrt{#it{s}} = 13.6 TeV"], 
        [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
      ]
    }
  },
  "output": {
    
    "output_file_name": "output/analysis/MC_tails_extraction/"
  }
}

# Floating Parameter    FinalValue +/-  Error
#   --------------------  --------------------------
#                     aa    5.7617e-01 +/-  5.29e-06
#            alphaL_Jpsi   -8.4264e-01 +/-  4.78e-04
#            alphaR_Jpsi    2.0054e+00 +/-  2.07e-03
#                     bb    4.2799e-01 +/-  1.24e-05
#                    bkg    5.0541e+06 +/-  7.10e+01
#                     cc    1.0541e-01 +/-  1.04e-06
#              mean_Jpsi    3.0766e+00 +/-  5.01e-06
#               p1L_Jpsi    1.5681e-01 +/-  4.42e-05
#               p1R_Jpsi    3.4342e-02 +/-  3.92e-04
#               p2L_Jpsi    8.4235e-01 +/-  3.22e-04
#               p2R_Jpsi    1.2939e+00 +/-  1.05e-01
#               p3L_Jpsi    2.5171e-03 +/-  4.99e-05
#               p3R_Jpsi    7.5424e-03 +/-  2.26e-04
#               sig_Jpsi    9.2710e+05 +/-  3.78e+01
#             width_Jpsi    9.2478e-02 +/-  4.36e-06


# Floating Parameter    FinalValue +/-  Error
#   --------------------  --------------------------
#                     aa    3.7063e-02 +/-  2.74e-06
#            alphaL_Jpsi   -8.2499e-01 +/-  4.14e-03
#            alphaR_Jpsi    1.9942e+00 +/-  1.23e-03
#                     bb    3.9900e-01 +/-  1.45e-04
#                    bkg    5.0337e+06 +/-  5.76e+02
#                     cc    6.4113e-03 +/-  4.76e-07
#              mean_Jpsi    3.0764e+00 +/-  8.79e-05
#               p1L_Jpsi    1.5782e-01 +/-  2.79e-04
#               p1R_Jpsi    2.6443e-02 +/-  2.35e-02
#               p2L_Jpsi    1.0542e+00 +/-  7.86e-03
#               p2R_Jpsi    5.2821e-01 +/-  1.57e+00
#               p3L_Jpsi    1.0037e-02 +/-  8.52e-04
#               p3R_Jpsi    6.6852e-02 +/-  2.58e-02
#               sig_Jpsi    9.4442e+05 +/-  4.17e+02
#             width_Jpsi    9.1953e-02 +/-  7.41e-05