{
  "input": {
    "input_file_name": "/Users/nicolasbize/alice/fresh-analysis/Analysis_Data/psi2sToJpsi/LHC22o_full_stat/differential_pT_y.root",
    "input_name": ["pT_y_integrated"],
    "pdf_dictionary": {
      "pdf": ["NA60", "NA60", "VWG", "SUM"],
      "pdfName": ["Jpsi", "Psi2s", "Bkg", "SUM"],
      "pdfColor": [861, 417, 1],
      "pdfNameForLegend": ["J/#psi", "#psi(2S)","Background", "Fit"],
      "pdfStyle": [1, 1, 2],
      "parVal": [
        [3.097, 1.2e-01,  4., 0.01, 0.44, 0.223, 2., 0.184, 1.295,  0.065],
        [3.68, 1.5e-01,  2.5, 0.0028, 0.4401, 0.2234, 2., 0.184, 1.295,  0.065],
        [1, 1, 1],
        [1.e+6, 100000, 1.e+6]
      ],
      "parLimMin": [
        [2.8, 7.0e-02,  0., 0., 0., 0., 0., 0., 0.,  0.],
        [3.68, 7.0e-02, 2.5, 0.0028, 0.4401, 0.2234, 2., 0.184, 1.295,  0.065],
        [-10, 0, -100],
        [10, 1, 10]
      ],
      "parLimMax": [
        [3.2, 1.9e-01,    5., 2., 3., 2., 15., 3., 3., 2.],
        [3.68, 1.9e-01,   2.5, 0.0028, 0.4401, 0.2234, 2., 0.184, 1.295,  0.065],
        [10, 100, 100],
        [1.9e+6, 5.e+5, 1.e+8]
      ],
      "parName": [
        ["mean_Jpsi", "width_Jpsi", "alphaL_Jpsi", "p1L_Jpsi", "p2L_Jpsi", "p3L_Jpsi", "alphaR_Jpsi", "p1R_Jpsi", "p2R_Jpsi", "p3R_Jpsi"],
        ["sum::mean_Psi2s(mean_Jpsi,0.584)", "prod::width_Psi2s(width_Jpsi)", "alphaL_Jpsi", "p1L_Jpsi", "p2L_Jpsi", "p3L_Jpsi", "alphaR_Jpsi", "p1R_Jpsi", "p2R_Jpsi", "p3R_Jpsi"],
        ["aa", "bb", "cc"],
        ["sig_Jpsi", "sig_Psi2s", "bkg"]
      ],
      "fitRangeMin": [2],
      "fitRangeMax": [5],
      "fitMethod": "likelyhood",
      "doResidualPlot": true,
      "doPullPlot": true, 
      "doCorrMatPlot": true,
      "doAlicePlot": true,
      "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi", "sig_Psi2s"],
      "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}", "#it{N}_{#psi(2S)}"],
      "text": [
        [0.20, 0.87, "LHC22o NA60+VWG, #sqrt{#it{s}} = 13.6 TeV"], 
        [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
      ]
    }
  },
  "output": {
    
    "output_file_name": "output/analysis/LHC22o_full_stat_apass4_tails_extraction/"
  }
}

# "parVal": [
#         [3.097, 1.2e-01,  -0.83, 0.01, 0.44, 0.223, 2., 0.184, 1.295,  0.065],
#         [3.68, 1.5e-01,  -0.8303, 0.0028, 0.4401, 0.2234, 2., 0.184, 1.295,  0.065],
#         [1, 1, 1],
#         [1.e+6, 100000, 1.e+6]
#       ],
#       "parLimMin": [
#         [2.8, 7.0e-02,  -5., 0., 0., 0., -5., 0., 0.,  0.],
#         [3.68, 7.0e-02, -0.8303, 0.0028, 0.4401, 0.2234, 2., 0.184, 1.295,  0.065],
#         [-10, 0, -100],
#         [100, 1, 100]
#       ],
#       "parLimMax": [
#         [3.2, 1.5e-01,    1., 3, 3., 3., 5., 3., 3., 2.],
#         [3.68, 1.9e-01,   -0.8303, 0.0028, 0.4401, 0.2234, 2., 0.184, 1.295,  0.065],
#         [10, 100, 100],
#         [2.e+6, 5.e+5, 1.e+8]